name: Schedule cli
on:
  workflow_run:
    workflows: ["Pre submits cli"]
    types: [completed]
    branches: [main]

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}

jobs:
  if-failed:
    runs-on: ubuntu-latest
    # See https://github.com/orgs/community/discussions/26238.
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: event_name
      - name: Check event name
        id: name
        run: |
          name=$(cat ./event_name.txt)
          ctned="false"
          if [[ "$name" == "schedule" ]] || [[ "$name" == "workflow_dispatch" ]]; then
            ctned="true"
          fi
          echo "continue=$ctned" >> $GITHUB_OUTPUT
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        if: steps.name.outputs.continue == 'true'
        with:
          ref: main
          repository: slsa-framework/example-package
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion != 'success'
      - run: ./.github/workflows/scripts/e2e-report-success.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion == 'success'
