name: Actions pre submits

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Rebuild the dist/ directory
        working-directory: actions/installer
        run: make package

      - name: Compare the expected and actual dist/ directories
        working-directory: actions/installer
        id: diff
        run: |
          set -euo pipefail
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi

      # If index.js was different from expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
