# Rebuild the /dist folder of our github action.
# While renovate-bot can bump versions in package.json and package-lock.json,
# it doesn' have the ability to run our `make package` script.
# As a pull_request_target event, this workflow is triggered by PRs,
# but runs withing the context of a repo, and outside of the PR
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

on:
  pull_request_target:

# example from
# https://github.com/actions/checkout/blob/cd7d8d697e10461458bc61a30d094dc601a8b017/README.md#push-a-commit-using-the-built-in-token
jobs:
  update-dists:
    runs-on: ubuntu-latest
    steps:
      - id: git-init
        uses: actions/checkout@v4
      - id: checkout-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
      - id: repackage
        run: |
          (
            cd ./actions/installer && \
            make clean && \
            make package && \
            true
          )
      - id: commit-and-push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git diff --exit-code && \
            git add . && \
            git commit -m "update dists" && \
            git push
