# Rebuild the /dist folder of our github action.
# While renovate-bot can bump versions in package.json and package-lock.json,
# it doesn' have the ability to run our `make package` script to rebuild the `dist/` folder
# that contains the final javasctipt code to be executed. This workflow rebuilds the javascript
# and adds the changes as a commit to the triggering PR.
# As a pull_request_target event, this workflow is triggered by PRs,
# but runs withing the context of a repo, and outside of the PR
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
# We use a separate job for executing the PRs untrusted code.
# We avoid using `git apply` because there may be more vulnerabilities: https://github.blog/2023-02-14-git-security-vulnerabilities-announced-3/
# maybe use `actions/upload-artifact` for every changed file, if path is preserved.

# TODO: use fine-grained token scoped to renovate-bot's fork

on:
  pull_request_target:
    paths:
      - ./actions/installer/**
    branches:
      - main

env:
  ARTIFACT_NAME: dist.tar
  DIST_FOLDER: ./actions/installer/dist

# example from
# https://github.com/actions/checkout/blob/cd7d8d697e10461458bc61a30d094dc601a8b017/README.md#push-a-commit-using-the-built-in-token
jobs:
  rebuild:
    # if: github.event.sender.login == 'renovate-bot'
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - id: details
        run: |
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.sender.name }}
          echo echo ${{ github.event.pull_request.user.login }}
          echo echo ${{ github.event.pull_request.user.name }}
      - id: git-init
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - id: rebuild
        run: |
          (
            cd ${{ env.DIST_FOLDER }}/../ && \
            make clean && \
            make package && \
            true
          )
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.DIST_FOLDER }}

  push:
    needs: [rebuild]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - id: git-init
      uses: actions/checkout@v4
    - id: checkout-pr
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr checkout ${{ github.event.pull_request.number }}
    - id: prep
      run:  |
        rm -rf ${{ env.DIST_FOLDER }}
    - id: download
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
    - id: push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add .
        if git commit -m "update ${{ env.DIST_FOLDER }}"
        then
          git push
        else
          echo "no changes"
        fi
